apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uvrl9dt2j-java-quarkus
  janus-idp.io/tekton: uvrl9dt2j-java-quarkus
  backstage.io/kubernetes-id: uvrl9dt2j-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uvrl9dt2j-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
